# Site Info
title: ""
tagline: ""
description: ""
baseurl: ""
url: https:/youngmoon525.github.io
logo: ""

# Site configurations
#gems:
#  - jekyll-paginate
#markdown: kramdown
#kramdown:
#  input: GFM
#excerpt_separator: "<!-- more -->"
sass:
  style: compressed
  sass_dir: _scss
#paginate:
#paginate_path: ''
#permalink: pretty

version: 1.0.0

# About/contact
author:
  name: Ym Kim
  description: Ym Kim
  contact:
    # linkedin:  https://www.linkedin.com/in/
    github:    https://github.com/youngmoon525
    #    facebook:
    # twitter:
    # weibo:
    email:    mailto:youngmoon525@naver.com

google_analytics:
  ua: 'UA-134234881-1'
